#!/usr/bin/env bash
if [ "$2" == "clone" ]; then
  git clone https://github.com/redstage/docker-linux-m1.git $1 && cd $1;
fi

sudo chmod u+x ./*

if [ "$3" ]; then
  docker image pull viniciusbord9/magento1:$3
else
  docker image pull viniciusbord9/magento1
fi

if [ "$(uname)" == "cygwin" ] || [ "$(uname)" == "msys" ] || [ "$(uname)" == "win32" ]; then
  git checkout -f mac;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml
else
  git checkout -f master;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;
fi

if [ "$3" ]; then
  sed -i '' -e "s/<php_version>/$3/g" Dockerfile;
  sed -i '' -e "s/<php_version>/$3/g" docker-compose.yml;
else
  sed -i '' -e "s/<php_version>/5.5/g" Dockerfile;
  sed -i '' -e "s/<php_version>/latest/g" docker-compose.yml;
fi

if [ ! -e src/index.php ]; then
  echo "<?php phpinfo();" > src/index.php;
fi

if [ -d src/app/etc ]; then  
  if [ ! -e src/app/etc/local.xml ]; then
    cp -rv .docker/users/local.xml.sample src/app/etc/local.xml;
  fi
fi

bash start
